on: [push, pull_request, workflow_dispatch]

jobs:
  build-HyperC:
    runs-on: docker
    container:
      image: nixos/nix
    name: Build NixOS Iso
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo /home/runner/externals/node20/bin >> $GITHUB_PATH
      - name: Get System Info
        run: nix-shell -p fastfetch --run "fastfetch" >> $GITHUB_PATH
