on: [push, pull_request, workflow_dispatch]

jobs:
  build-HyperC:
    runs-on: nixos
    name: "Builds HyperC"
    steps:
      - name: "Git Clone"
        run: git clone https://git.kb-one.de/kb01/aux-config .

      - name: "Nix Build"
        run: nix build --flake .#HyperC --no-link --no-update-lock-file --verbose
  build-LoyAdjo:
    runs-on: nixos
    name: "Builds HyperC"
    steps:
      - name: "Git Clone"
        run: git clone https://git.kb-one.de/kb01/aux-config .

      - name: "Nix Build"
        run: nix build --flake .#LoyAdjo --no-link --no-update-lock-file --verbose
  build-kb-games-01:
    runs-on: nixos
    name: "Builds HyperC"
    steps:
      - name: "Git Clone"
        run: git clone https://git.kb-one.de/kb01/aux-config .

      - name: "Nix Build"
        run: nix build --flake .#kb-games-01 --no-link --no-update-lock-file --verbose
