on: [push, pull_request, workflow_dispatch]

jobs:
  build-HyperC:
    runs-on: docker
    container:
      image: ghcr.io/lix-project/lix:latest
    name: "Check NixOS Configuration"
    steps:
      - name: "Git Clone"
        run: git clone https://git.kb-one.de/kb01/aux-config .

      - name: "Nix Flake Update"
        run: nix flake update --experimental-features 'nix-command flakes'

      - name: "Check evaluation"
        run: nix flake check --no-build --all-systems --experimental-features 'nix-command flakes'

      - name: "Do linting"
        run: nix run nixpkgs#statix -- check . --experimental-features 'nix-command flakes'

      - name: "Check formatting"
        run: nix fmt -- --fail-on-change --experimental-features 'nix-command flakes'
