on: [push, pull_request, workflow_dispatch]

jobs:
  test-build:
    runs-on: nixos
    name: "Check NixOS Configuration"
    steps:
      - name: "Git Clone"
        run: git clone https://git.kb-one.de/kb01/aux-config .

      - name: "Check evaluation"
        run: nix flake check --no-build --all-systems --experimental-features 'nix-command flakes'

      - name: "Do linting"
        run: nix run nixpkgs#statix -- check . --experimental-features 'nix-command flakes'

      - name: "Check formatting"
        run: nix fmt -- --fail-on-change --experimental-features 'nix-command flakes'
