on: [push, pull_request, workflow_dispatch]

jobs:
  build-HyperC:
    runs-on: docker
    container:
      image: ghcr.io/lix-project/lix:latest
    name: "Check NixOS Configuration"
    steps:
      - name: "Git Clone"
        run: |
          git clone https://git.kb-one.de/kb01/aux-config
          cd aux-config

      - name: "Check evaluation"
        run: nix flake check --no-build --all-systems

      - name: "Do linting"
        run: nix run nixpkgs#statix -- check .

      - name: "Check formatting"
        run: nix fmt -- --fail-on-change
