on: [push, pull_request, workflow_dispatch]

jobs:
  build-HyperC:
    runs-on: docker
    container:
      image: niteo/nixpkgs-nixos-unstable
    name: Build NixOS Iso
    steps:
      - name: Update Nix Store
        run: |
            nix-store --update
      - name: Get System Info
        run: |
            nix-shell -p fastfetch --run "fastfetch"
