on: [push, pull_request, workflow_dispatch]

jobs:
  flake-check:
    runs-on: nixos
    name: "Check Nix Flake"
    steps:
      - name: "Git Clone"
        run: git clone https://git.kb-one.de/kb01/aux-config .

      - name: "Check Nix Flake"
        run: nix flake check
