on: [push, pull_request, workflow_dispatch]

jobs:
  build-HyperC:
    runs-on: docker
    container:
      image: ghcr.io/lix-project/lix:latest
    name: "Check NixOS Configuration"
    steps:
      - name: "Use Node.js (Workarround)"
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Check evaluation"
        run: nix flake check --no-build --all-systems

      - name: "Do linting"
        run: nix run nixpkgs#statix -- check .

      - name: "Check formatting"
        run: nix fmt -- --fail-on-change
